version: '3'
services:
  app:
    build:
      context: ./config/docker
    command: ["bin/rails", "server", "--binding=0.0.0.0", "--port=3000", "--pid=/var/run/rails-server.pid"]
    volumes:
      - .:/root/app
      - bundle:/usr/local/bundle
      - storage:/root/app/storage
      - node_modules:/root/app/node_modules
      - rails_tmp:/root/app/tmp
    expose:
     - "3000"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /root/app
volumes:
  bundle:
  storage:
  node_modules:
  rails_tmp:
